---
abstract: ~
author:
  - 'Rob Kinyon <rob.kinyon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Plack: 1.0030
  Test::DBIx::Class: 0.01
  Test::Deep: 0.01
  Test::Exception: 0.21
  Test::More: 0.88
  Test::Warn: 0.01
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::Sims::REST
name: DBIx-Class-Sims-REST
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class::Sims: 0
  Hash::Merge: 0
  JSON::XS: 0
  Plack::Request: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.2
